"""Ticket + TicketEvent (M5). One ticket per conversation; state changes only via the
guarded CAS in ``domain.ticketing.transitions``."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.infra.db.base import Base, TenantMixin, TimestampMixin, uuid_pk


class Ticket(Base, TenantMixin, TimestampMixin):
    __tablename__ = "ticket"
    # [C2/IMP-TKT-4] exactly one ticket per conversation; creation is get-or-create.
    __table_args__ = (
        UniqueConstraint("tenant_id", "conversation_id", name="uq_ticket_tenant_conversation"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("conversation.id"), nullable=False
    )
    state: Mapped[str] = mapped_column(String(16), nullable=False, default="new")
    priority: Mapped[str] = mapped_column(String(8), nullable=False, default="normal")  # [C4]
    language: Mapped[str | None] = mapped_column(String(16))  # denormalised for filtering
    # Single nullable pointer, set only after a verified lookup (never a copy of fields).
    linked_record_type: Mapped[str | None] = mapped_column(String(32))
    linked_record_key: Mapped[str | None] = mapped_column(String(128))
    # After-hours follow-up address ([A15]) — kept distinct from any verified identity email.
    contact_email: Mapped[str | None] = mapped_column(String(320))
    assignee_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))  # claiming agent
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))  # reopen anchor
    escalated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))  # queue FIFO
    last_customer_msg_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # [IMP-TKT-4] the REOPENED state has no fixed outbound edge — it's "recompute where this
    # goes" — so the state/assignee it's reopening FROM are captured here for the router.
    prior_state: Mapped[str | None] = mapped_column(String(16))
    prior_assignee_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))


class TicketEvent(Base, TenantMixin, TimestampMixin):
    """Append-only audit of every transition (tenant-scoped; tenant_id auto-fills from GUC)."""

    __tablename__ = "ticket_event"

    id: Mapped[uuid.UUID] = uuid_pk()
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("ticket.id"), nullable=False, index=True
    )
    from_state: Mapped[str] = mapped_column(String(16), nullable=False)
    to_state: Mapped[str] = mapped_column(String(16), nullable=False)
    actor: Mapped[str] = mapped_column(String(16), nullable=False)  # ai|agent|system|customer


class ResolutionSummary(Base, TenantMixin, TimestampMixin):
    """The escalation/resolution summary artifact ([IMP-ESC-6]). One table; ``type``
    discriminates an escalation hand-off summary from a resolution close-out summary.

    The summary *text* itself is generated by M2 (the AI) — this module only owns storage and
    the Phase-1 stub write. ``summary`` is nullable so the row can exist as "pending" the
    instant the transition commits, before the async generation step (owned by M2/M9) fills it
    in — the caller must never block a state transition on LLM output.
    """

    __tablename__ = "resolution_summary"

    id: Mapped[uuid.UUID] = uuid_pk()
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("ticket.id"), nullable=False, index=True
    )
    type: Mapped[str] = mapped_column(String(16), nullable=False)  # escalation|resolution
    summary: Mapped[str | None] = mapped_column(Text)
    transcript_ref: Mapped[str | None] = mapped_column(String(200))
    kb_sources: Mapped[list | None] = mapped_column(JSONB)
    suggested_reply: Mapped[str | None] = mapped_column(Text)
    linked_record_ref: Mapped[str | None] = mapped_column(String(200))


class InternalNote(Base, TenantMixin, TimestampMixin):
    """Agent-only note on a ticket (M7) — never shown to the customer, unlike a reply."""

    __tablename__ = "internal_note"

    id: Mapped[uuid.UUID] = uuid_pk()
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("ticket.id"), nullable=False, index=True
    )
    staff_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
